CREATE SCHEMA ESTOQUEHUB;
USE ESTOQUEHUB;

CREATE TABLE CDCARGO (
	CDCARID INT UNSIGNED AUTO_INCREMENT,
  CDCARNOME VARCHAR(200) NOT NULL,

  PRIMARY KEY (CDCARID)
);

CREATE TABLE CDUSUARIO (
	CDUSID INT UNSIGNED AUTO_INCREMENT,
  CDUSNOME VARCHAR(100) NOT NULL,
  CDUSEMAIL VARCHAR(100) NOT NULL,
  CDUSCEL VARCHAR(20),
  CDUSSENHA VARCHAR(45) NOT NULL,
  CDUSCARGOID INT UNSIGNED,

  PRIMARY KEY (CDUSID),
  FOREIGN KEY (CDUSCARGOID) REFERENCES CDCARGO(CDCARID)
);

CREATE TABLE CDPRODUTO(
	CDPRODID INT UNSIGNED AUTO_INCREMENT,
  CDPRODNOME VARCHAR(100) NOT NULL,
  CDPRODDESC VARCHAR(200) NOT NULL,
  CDPRODPRECO DECIMAL(10, 2) NOT NULL,

  PRIMARY KEY (CDPRODID)
);

CREATE TABLE CDESTOQUE(
	CDESTUSUARIOID INT UNSIGNED,
  CDESTPRODID INT UNSIGNED,
  CDESTQTDPROD INT NOT NULL,

  FOREIGN KEY (CDESTUSUARIOID) REFERENCES CDUSUARIO(CDUSID),
  FOREIGN KEY (CDESTPRODID) REFERENCES CDPRODUTO(CDPRODID)
);

CREATE TABLE SESSION(
	SESSIONID INT,
  SESDTCREATE DATETIME NOT NULL,
  SESUSUARIOID INT UNSIGNED,

  PRIMARY KEY (SESSIONID),
  FOREIGN KEY (SESUSUARIOID) REFERENCES CDUSUARIO(CDUSID)
);
